CREATE DATABASE IF NOT EXISTS library_management_system;
USE library_management_system;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) DEFAULT NULL,
    full_name VARCHAR(150) DEFAULT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'borrower',
    first_name VARCHAR(100) DEFAULT NULL,
    last_name VARCHAR(100) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    profile_image VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name VARCHAR(150) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS password VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'borrower',
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(100) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(30) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS profile_image VARCHAR(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Active',
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    isbn VARCHAR(20) DEFAULT NULL,
    author VARCHAR(150) NOT NULL,
    publisher VARCHAR(150) DEFAULT NULL,
    publication_year SMALLINT DEFAULT NULL,
    category VARCHAR(100) NOT NULL,
    cover_image VARCHAR(255) DEFAULT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1,
    available_copies INT UNSIGNED NOT NULL DEFAULT 1,
    description TEXT DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Available',
    borrower_name VARCHAR(150) DEFAULT NULL,
    borrowed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, full_name, email, password, password_hash, role)
SELECT 'System Administrator', 'System Administrator', 'admin@gmail.com', 'admin123', 'admin123', 'admin'
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE email = 'admin@gmail.com'
);
